megano/app_megano/urls.py
from os import name
from django.urls import path,include
from django.conf.urls import url
from . import views

urlpatterns = [
    path('megano',views.Main.as_view(),name = "main"),
    path('megano/authorization',views.Login.as_view(),name="authorization"),
    path('megano/logout',views.UserLogoutView.as_view(),name="logout"),
    path('megano/registration',views.RegisterUserView.as_view(),name="registration"),
    path('megana/catalog',views.CatalogView.as_view(),name='catalog'),
    url(r'', views.CatalogView.as_view(),name='catalog_filter')
]

megano/megano/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_megano.urls'))
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

megano/app_megano/models.py
from itertools import product
from pyexpat import model
from statistics import mode
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.fields import BooleanField, CharField
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=500,verbose_name=("название"))
    icon=models.FileField(upload_to='product/',blank=True,null=True,verbose_name=("иконка"))
    

    class Meta():
        verbose_name_plural="categories"
        verbose_name = "category"
        db_table = "Category"

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    category = models.ManyToManyField(Category, verbose_name='Категория')
    name = models.CharField(max_length=25, unique=True, verbose_name='Название')
    icon=models.FileField(upload_to='icon/',blank=True,null=True,verbose_name=("иконка"))

    class Meta:
        verbose_name_plural = 'Subcategories'
        verbose_name = 'Subcategory'
        db_table = "SubCategory"

    def __str__(self):
        return self.name

class Role(models.Model):
    name = CharField(max_length=500,verbose_name="роль")

    class Meta:
        verbose_name_plural = 'Roles'
        verbose_name = 'Role'
        db_table = "Role"
         
    def __str__(self):
        return self.name


class User(AbstractUser):
    city = models.CharField(max_length=500,blank=True,null=True,verbose_name="город")
    age = models.IntegerField(blank=True,null=True,verbose_name="возраст")
    phone = models.CharField(max_length=12,blank=True,null=True,unique=True,verbose_name="телефон")
    balance = models.FloatField(default=0,verbose_name="баланс")
    role = models.ForeignKey(Role,on_delete=models.CASCADE,verbose_name="роль",blank=True,null=True)
    photo=models.FileField(upload_to='user_photo/',blank=True,null=True,verbose_name=("фото пользователя"))

    def __str__(self):
        return self.username

class Product(models.Model):
    name = models.CharField(max_length=500,verbose_name="наименования")
    description = models.CharField(max_length=5000,verbose_name="описание")
    category = models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name="категория")
    count = models.IntegerField(default=0,verbose_name="колличество")
    price = models.FloatField(default=0,verbose_name="цена")
    limited = models.BooleanField(default=False,verbose_name="ограниченный тираж")


    class Meta:
        verbose_name_plural = 'Products'
        verbose_name = 'Product'
        db_table = "Product"

    def __str__(self):
        return self.name

class Photo(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE,verbose_name="продукт")
    photo = models.FileField(upload_to='product_photo/',blank=True,null=True,verbose_name=("фото продукта"))
    general = models.BooleanField(default=False,verbose_name="главное")

    class Meta:
        verbose_name_plural = 'Photos'
        verbose_name = 'Photo'
        db_table = "Photo"

    def __str__(self):
        return f"Фото продукта {self.product}"

class Cart(models.Model):
    owner = models.OneToOneField(User,on_delete=models.CASCADE,verbose_name="id владелеца")
    
    class Meta:
        verbose_name_plural = 'Carts'
        verbose_name = 'Cart'
        db_table = "Cart"

    def __str__(self):
        return f'Козрина пользователя {self.owner}'

class CartItems(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE,verbose_name="корзина")
    product_id = models.IntegerField(verbose_name="id_товарa")
    count = models.IntegerField(default=0,verbose_name= 'количество')
    data = models.DateField(auto_now=True,verbose_name="дата")

    class Meta:
        verbose_name_plural = 'CartItems'
        verbose_name = 'CartItem'
        db_table = "CartItem"

    def __str__(self):
        return f'{self.cart} - id товара {self.product_id }'

class Review(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE,verbose_name="товар")
    user_name = models.CharField(max_length=100,default="Гость",verbose_name="пользователь")
    text = models.TextField(max_length=5000,verbose_name="текст")
    data = models.DateField(auto_now=True,verbose_name="дата")

    class Meta:
        verbose_name_plural = 'Reviews'
        verbose_name = 'Review'
        db_table = "Review"

    def __str__(self):
        return f"Отзыв пользователя {self.user_name} о товре {self.product}"

class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True,verbose_name="пользователь")
    data = models.DateField(auto_now=True,verbose_name="дата")
    price = models.IntegerField(default=0,verbose_name= 'цена')
    status = models.BooleanField(default=False,verbose_name='статус')

    class Meta:
        verbose_name_plural = 'Orders'
        verbose_name = 'Order'
        db_table = "Order"

    def __str__(self):
        return f"Заказ № {self.id} - пользователь {self.user}"

class OrderItem(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE,verbose_name="заказ")
    product = models.ForeignKey(Product,on_delete=models.CASCADE,verbose_name="товар")
    count = models.IntegerField(default=0,verbose_name= 'количество')

    class Meta:
        verbose_name_plural = 'OrderItems'
        verbose_name = 'OrderItem'
        db_table = "OrderItem"

    def __str__(self):
        return f"{self.order} - товар {self.product}"

megano/app_megano/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from app_megano.models import  User


class RegisterUserForm(UserCreationForm):
    
    class Meta:
        model=User
        fields=["first_name","last_name","username",'age','phone','email','city','photo','password1','password2']

megano/app_megano/views.py
from re import template
from tkinter import Widget
from django import forms
from django.shortcuts import render
from django.views.generic.base import View
from django.views.generic import ListView
from django.contrib.auth.views import LoginView,LogoutView
from django.urls.base import reverse_lazy
from django.contrib.auth import authenticate, login
from django.http.response import HttpResponseRedirect
from  django.views.generic.edit import FormView
from app_megano.models import User,Role,Product
from app_megano.forms import RegisterUserForm
from app_megano.services import Carts,Reviews,Buy
import django_filters



class Main(View):
    def get(self,request):
        cart = Buy(request)
        cart.pay_order(1)
        return render(request,'app_megano/index.html',{})

class Login(LoginView):
    template_name= 'app_megano/login.html'

    def form_valid(self, form):
        user = form.get_user()
        login(self.request,user)
        return HttpResponseRedirect(self.get_success_url())

class UserLogoutView(LogoutView):
    next_page=reverse_lazy('main')


class RegisterUserView(FormView):
    form_class = RegisterUserForm
    template_name = 'app_megano/register.html'
    success_url = reverse_lazy("main")

    def form_valid(self, form):
        user = form.save(commit=False)

        user.role = Role.objects.get(id=2)
        form.save()
        username = form.cleaned_data['username']
        password=form.cleaned_data['password1']
        user=authenticate(username=username,password=password)
        login(self.request,user)
        return HttpResponseRedirect(self.get_success_url())



class ProductFilter(django_filters.FilterSet):
    price = django_filters.RangeFilter(widget=forms.widgets.TextInput(attrs={'class': 'myfieldclass'}))
    
    class Meta:
        model = Product
        fields = ["price"]

class CatalogView(ListView):
    model = Product
    template_name = "app_megano/catalog.html"
    filter_class = ProductFilter

    def get_queryset(self):
        queryset = super().get_queryset()
        self.f = self.filter_class(self.request.GET, queryset=queryset)
        return self.f.qs
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all()
        context['filter'] = self.f
        return context

megano/app_megano/templates/app_megano/catalog.html
{% extends "app_megano/base.html" %}
{% load static %}
{% load i18n %}
{% block title%}{% trans 'Megano' %}{% endblock title %}
{% block main %}
<div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Catalog Megano
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Catalog</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <form method="get">
                {% csrf_token %}
                {{filter.form.as_p}}
                <input type="submit" />
            </form>
            {% for obj in filter.qs %}
                {{ obj.name }} - ${{ obj.price }}<br />
            {% endfor %}
            <div class="Section-content">
                <div class="Cards">
                    {% for product in products%}
                        <div class="Card"><a class="Card-picture" href="#"><img src="{{product.photo_set.first.photo.url}}" alt="card.jpg"/></a>
                            <div class="Card-content">
                            <strong class="Card-title"><a href="product.html">{{product.name}}</a>
                            </strong>
                            <div class="Card-description">
                                <div class="Card-cost"><span class="Card-price">{{product.price}}</span></div>
                                <div class="Card-category">
                                    {{product.category.name}}
                                </div>
                                <div class="Card-hover"><a class="Card-btn" href="#"><img src="{% static '/img/icons/card/cart.svg' %}" alt="cart.svg"/></a></div>
                            </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

megano/app_megano/templates/app_megano/index.html
{% extends "app_megano/base.html" %}
{% load static %}
{% load i18n %}
{% block title%}{% trans 'Megano' %}{% endblock title %}

megano/app_megano/templates/app_megano/login.html
{% extends "app_megano/base.html" %}
{% load static %}
{% load i18n %}
{% block title%}{% trans 'Login' %}{% endblock title %}
{% block main %}
    <form class = "authorization_form"action="{% url 'authorization' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class = "btn btn-login" type="submit">{% trans "Войти" %}</button>
        <a class = "authorization__link" href="{% url 'registration' %}">Регистрация</a>
    </form>
{% endblock main %}

megano/app_megano/templates/app_megano/register.html
{% extends "app_megano/base.html" %}
{% load static %}
{% load i18n %}
{% block title%}{% trans 'Registration' %}{% endblock title %}
{% block main %}
    <form class = "registration_form"action="{% url 'registration' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class = "btn btn-registration" type="submit">{% trans "Регистрация" %}</button>
    </form>
{% endblock main %}